### ISSUE TITLE
Missing export function

### ISSUE THREAD

**Issue by Cogitaria** [mulesoft/api-designer#465] opened 2016-12-20 19:42 UTC
There's no export menu item and no hint as to how we are supposed to save the files created with api-designer.  To a person, everybody who has looked at this tool has asked that question and you also see posts such as "this is embarrasing, how do I save...", since it's such a basic need. 

There's no version on the menu, api-designer doesn't know what --version or -version means, but it's the latest as of 12/20/16 NPM module.

**Comment by Cogitaria** [comment] 2016-12-21 14:29
and ... no response

**Comment by jetmartin** [comment] 2017-01-09 19:52
Hi,

On a fresh NPM install my team get the same issue this morning.
More than the export button the right sidebar (HTML preview) is missing too.

It's maybe a bug on the latest NPM deployement because it works fine on my oldest installation.
When I re-install it, I reproduce the bug.

To fix this, what i've done bellow  : 
1 - clone the repo
2 - $ npm install && bower install && grunt build
      aparently the bower and grunt are not mandatory. (don't worry, the install and build are quite long)
3 - Then you need to run the dist folder on a local server.

Personnaly, i have browsersync on my computer so i did :
$ cd dist/
$ browser-sync start --server

You'r done.
I hope this help, i just fix it localy on my Windows 10, not tested yet on my team computers.

**Comment by sichvoge** [comment] 2017-01-19 16:16
We will look at that. Sorry for not coming back earlier @Cogitaria

**Comment by sichvoge** [comment] 2017-01-19 16:18
Very wierd by the way. Looking at our deployment its there http://rawgit.com/mulesoft/api-designer/master/dist/index.html#/?xDisableProxy=true.

![image](https://cloud.githubusercontent.com/assets/498114/22114889/e110f3e6-de62-11e6-83b4-8435a78ee8a5.png)

**Comment by sichvoge** [comment] 2017-01-19 16:22
Next, we will check the npm repo.

**Comment by agustinlg** [comment] 2017-01-24 18:46
Fixed installing latest 0.3.2

**Closed by agustinlg** 2017-01-24 18:46 UTC
