### ISSUE TITLE
API Designer Erased content of all RAML Files

### ISSUE THREAD

**Issue by jamesontriplett** [mulesoft/api-designer#394] opened 2016-05-31 22:14 UTC
I had a series of API RAML files in a folder on API designer, I moved all the api files out of the folder, and then deleted the folder.  At the same time I was trying to get the API portal to try to display my RAML files.  
I go to check my RAML files and they are all (except one) EMPTY!!!  I put a lot of work into those files.  I don't know what happened, but having them all erased is BAD!

**Comment by jamesontriplett** [comment] 2016-05-31 22:16
Where can I see previous saves or versions of my files???  I need to get that contact back.

**Comment by dmartinezg** [comment] 2016-06-01 12:45
Hi @jamesontriplett, can you provide more information about which API designer you were using?

 Are you self hosting API designer? Are you using a hosted version of API designer? If so, have you contacted support for the place where designer was hosted?

As for this being a bug on designer, we will look into it, and see if there is some interaction where saving can result in anything like that. Persistence is usually handled by the host of API designer.
Any information you can remember about which where the actions you performed will help us in debugging, so that this does not happen again to you or anybody else.

Thanks

**Comment by jamesontriplett** [comment] 2016-06-01 12:46
This was on Anypoint online platform.

**Comment by Gregroam** [comment] 2016-07-07 23:45
This happened to one of my files too when I renamed the folder it was in, then the file itself

**Comment by sichvoge** [comment] 2016-07-12 11:14
@jamesontriplett @Gregroam can you describe step by step what you have done? I think that might be because of the saving behaviour, but it would be good to have something that we can use to reproduce that.

**Comment by carowright** [comment] 2016-10-24 14:08
Already fixed in develop branch. Will be released in next version.

**Closed by carowright** 2016-10-24 14:08 UTC
Labels: bug, major
