### ISSUE TITLE
Cannot delete empty folder

### ISSUE THREAD

**Issue by brentryan** [mulesoft/api-designer#310] opened 2015-06-16 14:28 UTC
I have an empty folder in the designer that I can't delete.  When I select delete it gives me an error "The file cannot be deleted" and the folder disappears.  But if you refresh it comes back.

**Comment by dmartinezg** [comment] 2015-06-16 14:30
Thanks @brentryan, we'll take a look.

**Comment by sichvoge** [comment] 2015-06-28 14:58
Can't happen to reproduce that. It has been the same just once for me, but then trying to reproduce it couple of time - nothing. :/

@brentryan can you try again with the current master and let us know if you have the same problem!

**Comment by brentryan** [comment] 2015-07-02 02:03
@sichvoge I just tried this again and got the error

Bad Request

This file cannot be deleted

I did this within api designer here https://anypoint.mulesoft.com/apiplatform/brentryan/admin/#/organizations/1e4c4284-702e-421f-a318-10625ed74a45/dashboard/apis/16831/versions/17965/designer#answers

I have an empty folder that I'm trying to delete, but can't....

**Comment by Gregroam** [comment] 2016-06-30 01:26
I'm having this issue too... And this post was a year ago

**Comment by sichvoge** [comment] 2016-06-30 12:15
Are you using the master version here on Github or the one hosted on the Anypoint Platform? Using the hosted solution, I cannot reproduce it anymore.

**Comment by sichvoge** [comment] 2016-06-30 12:21
Same with the standalone version. :(

**Comment by Gregroam** [comment] 2016-06-30 22:42
The one hosted on AnyPoint.

1. Create folder
2. Add raml file to the folder with the version and a title. It'll give an error saying the file doesn't exist.
3. Refresh page. The error is gone
4. Delete the folder. It'll error but disappear
5. Refresh the page, folder is still there, it is now empty, but cannot be deleted. Keeps giving error

**Comment by sichvoge** [comment] 2016-07-01 12:48
I can confirm the very strange error in step 2, but not the others. Recorded it. Here's the gif.

![aodjy1tenw](https://cloud.githubusercontent.com/assets/498114/16521961/6c604ab6-3f92-11e6-9b3f-cfd52727a34c.gif)

**Comment by sichvoge** [comment] 2016-07-27 17:51
This strangely happened to me today :D But there was no way to replicate it.

**Comment by Gregroam** [comment] 2016-07-27 21:53
Hasn't happened to me in a while now, but I still export my project as a backup if I'm moving files from one folder to another just in case

**Comment by sichvoge** [comment] 2016-07-29 15:00
It really seems to happen randomly. :(

**Comment by carowright** [comment] 2016-10-24 15:06
Already fixed in develop branch. Will be released in next version.

**Closed by carowright** 2016-10-24 15:06 UTC
Labels: bug, major
