### ISSUE TITLE
Error when run api-designer

### ISSUE THREAD

**Issue by jvargasbdb** [mulesoft/api-designer#518] opened 2018-06-08 16:37 UTC
Before install api-designer with npm install -g api-designer and run api-designer in console, this genere this error

module.js:540
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jvarg25/.nvm/versions/node/v8.9.4/lib/node_modules/api-designer/bin/api-designer.js:6:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by Northshoot** [comment] 2018-06-09 18:01
getting same error

**Comment by yegorjke** [comment] 2018-06-22 06:20
+1

Why is `request` is not a dependency?

**Comment by shisama** [comment] 2018-07-25 01:44
Package version is old on npmjs.com. Latest is 0.4.13 on master branch.
Try the below command to install the latest version.

```
npm install -g mulesoft/api-designer#master
```

**Comment by carowright** [comment] 2018-09-17 15:30
Duplicate of #506

**Closed by carowright** 2018-09-17 15:30 UTC

**Comment by sapnahargunani** [comment] 2020-09-12 13:33
None of the above solution is working for me. Keep getting below error:
module.js:340
    throw err;
Could anyone please prove proper set of instructions?
