### ISSUE TITLE
Console renders even with an error in the RAML file 

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#396] opened 2016-06-15 13:48 UTC
As you can see in the image below, the console renders despite the RAML having errors. That should not happen.

![image](https://cloud.githubusercontent.com/assets/498114/16082087/3c87e1e6-3308-11e6-8a78-5d075f657931.png)

**Comment by dmartinezg** [comment] 2016-06-15 15:34
That is incorrect @sichvoge, the console is rendering the _previous_ version of RAML that was valid.

Imagine this scenario, as you are typing, your RAML will be invalid more often than not (this is particularly true for slow typers), in those scenarios, the console would flicker on an off all the time.

This is WAD, and is not a bug. I will be closing this one if you don't mind.

**Closed by dmartinezg** 2016-06-15 15:34 UTC
