### ISSUE TITLE
Mocking Service Off

### ISSUE THREAD

**Issue by sdarwin** [mulesoft/api-designer#356] opened 2015-09-23 21:15 UTC
Hello,
we just installed Mulesoft API Designer on a local machine and it appears to be working in every aspect except one, which is that the Mocking Service button says Off, and clicking On does not change it to On.  I am very new to this product, so the answer might be quite a simple one. What should be configured to turn this on?
Thanks, 
Sam

**Comment by sichvoge** [comment] 2015-09-25 15:56
You should be able to turn it on by simple clicking on the mocking service button. Can you add a GIF showing your use case.

**Comment by sdarwin** [comment] 2015-09-25 16:14
see attached screenshot.
this is on Ubuntu 14.04, node v4.1.0, cloud virtual machine, both firefox and chrome browsers.
nothing in particular has been set up or configured.  
![raml](https://cloud.githubusercontent.com/assets/1257803/10105782/9e94769c-637e-11e5-8146-1a1d5dc87f66.png)

**Comment by dmartinezg** [comment] 2015-09-25 16:20
Pretty interesting, how are you hosting designer?
Do you see any errors in the JS console?
Does the VM have access to the internet?

**Comment by sdarwin** [comment] 2015-09-25 17:16
>>Pretty interesting, how are you hosting designer?

npm install -g api-designer
api-designer

Do you see any errors in the JS console?
yes!   where www.example.com would be our server's name, here is the error:

http://www.example.com:3000/scripts/api-designer-vendor.js 21674

POST http://www.example.com:3000/proxy/http://mocksvc.mulesoft.com/mocks 404 (Not Found)

line 21674 is

xhr.send(post || null);

Does the VM have access to the internet?

its behind a firewall, but I can ping google and wget google, at least outgoing internet should be functioning.

**Comment by lowmemory** [comment] 2015-11-22 13:37
Any news?
I've the same problem.

Tried to git clone the project and build it but I got errors.

npm install

these are the last teminal lines:
...
7 verbose lifecycle api-designer@0.0.6~prepublish: CWD: /home/marco/Scrivania/RAML/api-designer
88 silly lifecycle api-designer@0.0.6~prepublish: Args: [ '-c', 'npm run build' ]
89 silly lifecycle api-designer@0.0.6~prepublish: Returned: code: 1  signal: null
90 info lifecycle api-designer@0.0.6~prepublish: Failed to exec prepublish script
91 warn EPEERINVALID grunt-autoprefixer@0.6.5 requires a peer of grunt@~0.4.2 but none was installed.
92 warn EPEERINVALID grunt-contrib-clean@0.4.1 requires a peer of grunt@~0.4.0 but none was installed.
93 warn EPEERINVALID grunt-contrib-concat@0.3.0 requires a peer of grunt@~0.4.0 but none was installed.
94 warn EPEERINVALID grunt-contrib-connect@0.3.0 requires a peer of grunt@~0.4.0 but none was installed.
95 warn EPEERINVALID grunt-contrib-copy@0.4.1 requires a peer of grunt@~0.4.0 but none was installed.
96 warn EPEERINVALID grunt-contrib-cssmin@0.9.0 requires a peer of grunt@~0.4.1 but none was installed.
97 warn EPEERINVALID grunt-contrib-jshint@0.6.5 requires a peer of grunt@~0.4.0 but none was installed.
98 warn EPEERINVALID grunt-contrib-less@0.7.0 requires a peer of grunt@~0.4.0 but none was installed.
99 warn EPEERINVALID grunt-contrib-uglify@0.2.7 requires a peer of grunt@~0.4.0 but none was installed.
100 warn EPEERINVALID grunt-contrib-watch@0.5.3 requires a peer of grunt@~0.4.0 but none was installed.
101 warn EPEERINVALID grunt-karma@0.8.3 requires a peer of grunt@0.4.x but none was installed.
102 warn EPEERINVALID grunt-protractor-runner@0.2.5 requires a peer of grunt@~0.4.1 but none was installed.
103 warn EPEERINVALID grunt-usemin@2.0.2 requires a peer of grunt@~0.4.0 but none was installed.
104 warn EPEERINVALID karma-chai-sinon@0.1.5 requires a peer of sinon@* but none was installed.
105 warn EPEERINVALID karma-chai-sinon@0.1.5 requires a peer of sinon-chai@* but none was installed.
106 warn EPACKAGEJSON api-designer@0.0.6 license should be a valid SPDX license expression
107 verbose stack Error: api-designer@0.0.6 prepublish: `npm run build`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
107 verbose stack     at emitTwo (events.js:87:13)
107 verbose stack     at EventEmitter.emit (events.js:172:7)
107 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
107 verbose stack     at emitTwo (events.js:87:13)
107 verbose stack     at ChildProcess.emit (events.js:172:7)
107 verbose stack     at maybeClose (internal/child_process.js:818:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
108 verbose pkgid api-designer@0.0.6
109 verbose cwd /home/marco/Scrivania/RAML/api-designer
110 error Linux 3.19.0-21-generic
111 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
112 error node v4.2.1
113 error npm  v3.3.10
114 error code ELIFECYCLE
115 error api-designer@0.0.6 prepublish: `npm run build`
115 error Exit status 1
116 error Failed at the api-designer@0.0.6 prepublish script 'npm run build'.
116 error Make sure you have the latest version of node.js and npm installed.
116 error If you do, this is most likely a problem with the api-designer package,
116 error not with npm itself.
116 error Tell the author that this fails on your system:
116 error     npm run build

**Comment by sichvoge** [comment] 2015-11-22 20:07
We'll investigate. Thank you again for raising it.

**Comment by sdarwin** [comment] 2015-11-23 19:10
> I've the same problem.
actually, it's probably a different issue.

> Tried to git clone the project and build it but I got errors.
I did not get errors building the project.       The problem was only a very small and specific one:  "Mocking Service Off".  it wouldn't turn on.

BTW, we are using https://github.com/colthreepv/express-raml-store, you might check that out, its a wrapper to api-designer.   If you get express-raml-store running, then you will have api-designer also.

**Comment by jamesHau** [comment] 2016-01-05 12:42
This helped me.

1. Fix RAML.Settings.proxy
In the javascript console you have to reset the RAML.Settings.proxy property.
So I ran 
delete RAML.Settings.proxy

2. Enable CORS
Since I'm using chrome I just took a plugin from the market and enabled it. (I took the one by vitvad)
Enable it when you are in the api-designer.

And now it worked for me. GL

**Comment by R0cKET** [comment] 2016-03-28 18:41
+1

**Comment by dcsw** [comment] 2016-09-16 22:12
I just confirmed the symptom that the Mocking Service button will not turn on when api-designer is installed via npm (eg 'npm install -g api-designer'), but that cloning the repo and running it (after 'npm install && bower install') DOES make the button work.

Perhaps the next push to npm (http://www.npmjs.com) will solve this issue and allow it to be closed.

**Comment by jefhu** [comment] 2017-01-21 03:34
I clone the git and run 'npm install && bower install'.  It builds js in dist/scripts/*.js

**Comment by sichvoge** [comment] 2017-01-21 12:13
really weird. thanks for reporting that!

**Comment by agustinlg** [comment] 2017-01-24 18:47
As a workaround, you can open it like this `http://localhost:3000/#/?xDisableProxy=true`

**Comment by sichvoge** [comment] 2017-01-24 18:58
@agustinlg should we update the documentation?

**Comment by qileilove** [comment] 2017-12-08 15:11
@agustinlg I use `http://localhost:3000/#/?xDisableProxy=true` to open, still has the issue, the turn on button always loading, then failed.
![image](https://user-images.githubusercontent.com/3895501/33771511-30d12d4e-dc6c-11e7-963c-bb3acb334e55.png)

**Comment by linonetwo** [comment] 2018-02-05 06:18
I'm in the same situation, maybe because it's showing ```file with path="/iresearch.raml.meta" does not exist``` ?

**Comment by carowright** [comment] 2018-03-23 17:28
Hi @linonetwo! 

Do you still reproduce this using version 0.4.10?

**Comment by linonetwo** [comment] 2018-03-24 01:48
Sorry but I leave changed the job so I don't quite know about it now...

**Comment by carowright** [comment] 2018-03-26 13:31
Closing this as cannot reproduce using version 0.4.10

**Closed by carowright** 2018-03-26 13:31 UTC
Labels: bug, minor

**Comment by Alejandro-Cansancio** [comment] 2020-04-25 07:25
Do we have a solution on this? Mocking service is still not working.
